apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-web
  namespace: demo-qa
  labels:
    project: demo
spec:
  replicas:  1
  selector:
    matchLabels:
      project: demo
      app: hello-world-web
  template:
    metadata:
      labels:
        app: hello-world-web
        project: demo
        app.kubernetes.io/name: HI
    spec:
      serviceAccountName: hello-world
      securityContext:
        runAsNonRoot: true
        runAsUser: 44444
        runAsGroup: 44444
      containers:
      - name: hello-world-web
        image: 277433404353.dkr.ecr.eu-central-1.amazonaws.com
        imagePullPolicy: Always
        args:
        - bash
        - -c
        - "/app.sh"
        env:
          - name: LISTEN_ADDRESS
            value: :8443
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "4Gi"
            cpu: "0.8"
        
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /
            port: 8443
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /hello
            port: 8443
          initialDelaySeconds: 30
          periodSeconds: 10
      nodeSelector:
        nodegroup: demo
        environment: qa

