apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: hello-world-role-binding
  namespace: demo-qa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hello-world
subjects:
- kind: ServiceAccount
  name: hello-world